#Addributeプラグインのコンフィグ

#エンティティからの攻撃による無敵時間の無効化(true:無効,false:無敵時間あり)
disableInvincibleTime: true

#ダメージ表示の有無(true:あり,false:なし)
displayDamage: true

#自然湧きのエンティティ(このプラグインによって召喚されたエンティティ以外)にステータスを持たせるかどうか
#(true: 持たせる, false:持たせない)
# ステータスが登録されていないエンティティのダメージ処理などはMinecraftのダメージ処理が使用されます
natureStatusHasEntity: true

#ステータスを持たせる対象外のエンティティ
#一部エンティティは強制的に対象外に指定されています(例: Item)
#またこのプラグインで召喚するエンティティにはこの設定は影響しません
#初期値として「ARMOR_STAND」が設定されていますが、外すこともできます
#ただ一部機能でアーマースタンドを使用しているためメモリ使用量また処理が大幅に増加する可能性があるため
#「ARMOR_STAND」を設定することを推奨します。
# エンティティの指定方法はsummonコマンドなので使用するエンティティの名前を全て大文字にしたものです
statusNotEntity: ["ARMOR_STAND"]

# ダメージ表示形式
# 表示されるダメージの表示内容を設定できます
# カラーコード(&数字)などでダメージに色を付けることができます。
# その場合は属性に設定した色コードが無効になります
# 例:
#  ??????.???で123.4の場合 → 123.4
#  ?????0.000で123.4の場合 → 123.400
#  ????で123.4の場合 → 123
displayDamageFormat: "?????0.00"

# ダメージの表示時間(tick:20=1秒)
displayDamageTime: 10

# ダメージ表示の最大数(「-1」にすると無制限になります)
displayDamageMax: -1

# ダメージ表示の拡散範囲
displayDamagePositionX: 0.3
displayDamagePositionY: 0.5
displayDamagePositionZ: 0.3

# 上下する最大地点(表示が上昇する場合の頂点,「2」の場合だと2ブロック分上昇します)
displayDamagePositionMaxY: 0.5

# クリティカルヒット率(パーセント表記)
criticalHit: 20

# エンティティのステータス更新タイミング(tick:20=1秒)
statusTime: 200

# アクションバーに表示する内容
# 特殊文字を使用することで現在の体力などを表示できます
# また & の後に 0 ~ 9 または a ~ g を書くことで色を付けることができます
# 特殊文字一覧
# %h  : 現在の体力
# @h  : 最大体力
# @ah : バフまたは装備による体力増加値
# %m  : 現在の魔力
# @m  : 最大魔力
# @am : バフまたは装備による魔力増加値
statusActionBar: "&f体力:&d%h&f/&d@h&e+@ah &f魔力:&5%m&f/&5@m&e+@am"
# 初期値は文字化けみたいに見えますが多分あってます(*'▽')

# アクションバーに表示する内容の更新頻度(tick:20=1秒)
statusActionBarTimer: 10

# ログレベルの設定
# この設定を変更することで出力されるログの範囲を決めることができます。
# 設定できる値は以下の５個になります
# DEBUG    : もっとも詳細なログ(バグや負荷を調べる際に使用する際のもの
# INFO     : 通常のログ (デフォルト)
# ERROR    : エラー、特に影響がないと思われる場合に出力される
# WARNING  : エラー、何かしら影響がある場合に出力される
# CRITICAL : 重大なエラー、プラグインが動作しない場合がある場合に出力される
# 上のどれかを設定することで設定したレベル以上のみ出力されるようになります。
logLevel: "INFO"