#属性の設定
#ここでは属性の追加や倍率の変更などの設定をすることができます
#属性は記述方法を守り記述することで追加することができます
#例は以下に記載しております
#またここには記載されていない特殊な属性として「default」「target」「nature」という属性があります
#この属性は以下の設定で追加せずとも自動で作成されます
#また「target」以外は以下で設定を記述することで設定を上書きすることができます。
#「target」は全ての属性の攻撃を無効にする効果付きの属性のため上書きすることができません。
# default:属性が無い場合の攻撃
# nature:自然影響(落下ダメージなど)
# target:全ての攻撃を無効化する属性(例:試し切り用など)


#↓これを消すと認識されなくなるので消さないでね(*'▽')
attributes:

  #属性の名前
  test1:
    #属性の表示名
    name: "test1"

    #ダメージ表示に使用する色
    #色の指定にはRGB値を使用します
    #RGB値とは色を３つの数値で表したものでRGBツールサイトなどで調べた数値をそれぞれ対応するところに書くことでその色を使用できます
    #どれかの値を負の値(「-1」など)にした場合、デフォルトの色が使用されます
    colorR: 225
    colorG: 0
    colorB: 0

    #弱点属性
    mags:
      #弱点属性の名前(自分自身を弱点に追加する事もできます)
      test1:
        #表示名(弱点属性の名前と同じにすることを推奨します)
        name: "test1"
        #倍率
        mag: 1.5

      #弱点属性は複数設定できますが同じ属性ものを設定することは出来ません
      test2:
        name: "test2"
        mag: 1.5

  #属性も上の記述方法を守ることで何個でも増やすことができます
  test2:
    name: "test1"
    colorR: 0
    colorG: 0
    colorB: 0
    mags:
      test1:
        name: "test1"
        mag: 1.5