#ステータス関係のコンフィグです


#ステータスの表示名========================================================================================================
#ステータスを表示する際に使用される名前です

#体力
healthName: "HP"

#自然体力回復( 「???」:バトルヒーリングスキルによる自動回復が10秒で600ポイントある。何時間攻撃しても俺は倒せない)
recoveryHealthName: "RHP"

#魔力
magicName: "MP"

#自然魔力回復
recoveryMagicName: "RMP"

#物理攻撃力
strengthName: "STR"

#魔法攻撃力
intelligenceName: "INT"

#防御力
vitalityName: "VIT"

#素早さ
agilityName: "AGI"

#経験値
expName: "EXP"

#レベル
levelName: "LV"

#=======================================================================================================================


#増加値====================================================================================================================
#ステータスの適応倍率の設定値です。
#例:体力のステータスが「20」の場合、増加値を「2」とした場合、実際の体力は「40」になります。
#そのため、実際に適応されるステータス値は「ステータス * 増加値」となります

#体力
healthValue: 1

#自然体力回復
recoveryHealthValue: 0.1

#魔力
magicValue: 1

#自然魔力回復
recoveryMagicValue: 0.1

#物理攻撃力
strengthValue: 1

#魔法攻撃力
intelligenceValue: 1

#防御力
vitalityValue: 1

#素早さ
agilityValue: 1

#=======================================================================================================================


#デフォルト値===============================================================================================================
#ステータスの初期値の設定

#名前
#名前の設定では「%n」と記述するとエンティティの表示名またはエンティティの種類に置き換わります
#また「&数字」で色を付けることもできます(色の種類については「minecraft color code」などで検索すると出てきます)
#例: プレイヤー(名前:Bakutaku)の場合
# 設定: [Admin]%n -> ゲーム内: [Admin]Bakutaku
# ※ 注意 名前が適応されるのはチャットとTabのプレイヤー一覧のみです(頭の上のは技術力に難しかった...(´・ω・`))
nameDefault: "%n"

#最大体力
maxHealthDefault: 20

#体力
healthDefault: 20

#自然体力回復
recoveryHealthDefault: 1

#最大魔力
maxMagicDefault: 20

#魔力
magicDefault: 20

#自然魔力回復
recoveryMagicDefault: 1

#物理攻撃力
strengthDefault: 0

#魔法攻撃力
intelligenceDefault: 0

#防御力
vitalityDefault: 0

#素早さ
agilityDefault: 0

#経験値
expDefault: 0

#落とす経験値
dropExpDefault: 5

#レベル
levelDefault: 0

#ステータスポイント
statusPointDefault: 5

#=======================================================================================================================


#レベルアップ=============================================================================================================
#レベルアップ時のステータスポイント付与値
#ステータスポイントを使用し他のステータスを強化していきます
levelUpAddStatusPoint: 1

#次のレベルアップに必要な経験値量
#必要な経験値を求める計算は「レベル ✕ LevelUpNeedExpPoint」で行っています
#また経験値はレベルが上がるたびにリセットされます
levelUpNeedExpPoint: 15

#=======================================================================================================================


#ダメージ=================================================================================================================
#ダメージの計算方法の設定
#ダメージを求める計算式を設定します
#使用できる記号は「+」「-」「*」「/」「^」「.」「(」「)」です
#「damage」などを式に入れることで計算時に「damage」が受けたダメージに置き換えられ計算されます
#物理攻撃力や魔法攻撃力などはすでにdamageに加算された状態になっています
#計算結果がマイナスになった場合は、倍率がマイナスの場合はそのまま適応され,そうではない場合は0になります
#プラグイン側が提供する数値(変数):
#   da    : 受けたダメージ
#   vit   : 防御力
#   mags  : ダメージ倍率(属性の相性による倍率合計)
#   ra    : 0以上1未満の乱数

calcDamage: "da * mags - vit"

#例 :
#ダメージが10,倍率が1.5,防御力が5の場合
#式: da * mags - vit
#結果: 10ダメージ
#
#ダメージが10,倍率が1.5,防御力が50の場合
#式: da * mags - vit
#結果: 0ダメージ
#
#ダメージが10,倍率が-1,防御力が5の場合
#式: da * mags - vit
#結果: 15回復

#=======================================================================================================================

